# kubernetes-templates/databases/mysql/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}-mysql-config
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: ${APP_NAME}-mysql
    app.kubernetes.io/part-of: ${APP_NAME}
data:
  MYSQL_DATABASE: "${DATABASE_NAME}"
  MYSQL_USER: "${DATABASE_USER}"