# kubernetes-templates/databases/mysql/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ${APP_NAME}-mysql-credentials
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: ${APP_NAME}-mysql
    app.kubernetes.io/part-of: ${APP_NAME}
stringData:
  MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
type: Opaque