# kubernetes-templates/databases/mysql/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-mysql-service
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: ${APP_NAME}-mysql
    app.kubernetes.io/part-of: ${APP_NAME}
spec:
  selector:
    app.kubernetes.io/instance: ${APP_NAME}-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306